spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Board?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 430441076561-70flabc0u3rmnsh80422ep3kantfd2vt.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  mvc:
    hidden-method:
      filter:
        enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: false
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always