spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 430441076561-70flabc0u3rmnsh80422ep3kantfd2vt.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: create